### ISSUE TITLE
Compilation Error (Because Incorrect Bug Fix)

### ISSUE THREAD

**Issue by enty8080** [thecakeisfalse/libinput#5]
Hello, @thecakeisfalse 

You fix for #4 caused this:

```
[Compiling] src/regexp.c
[Compiling] src/io.c
[Compiling] src/highlight.c
src/highlight.c: In function ‘add_pattern’:
src/highlight.c:37:39: error: ‘patters’ undeclared (first use in this function); did you mean ‘pattern’?
             patterns[index-1].color = patters[index].color;
                                       ^~~~~~~
                                       pattern
src/highlight.c:37:39: note: each undeclared identifier is reported only once for each function it appears in
Makefile:52: recipe for target 'build/highlight.o' failed
make: *** [build/highlight.o] Error 1
```

I can fix all vulnerabilities in your code, but you will close all my PRs like #2 . I do not know why you do not want to patch your code properly, or just let people who **knows** how to fix it to help you.

Regards,
Ivan Nikolsky (@enty8080)

**Comment by enty8080** [comment]
If you do not want me to help you with your vulnerable, full of memory leaks and incorrect memory allocation code, so I do not care anymore.

**Comment by thecakeisfalse** [comment]
@enty8080 ok, fixed
